#!/bin/bash

# Define command-line arguments

COMMAND_TYPE=$1
RESOURCE_TYPE=$2
NAMESPACE=$3

# Retrieve resource usage statistics from Kubernetes
kubectl $COMMAND_TYPE $RESOURCE_TYPE -n $NAMESPACE | tail -n +2 | while read line
do
  # Extract CPU and memory usage from the output
  NAME=$(echo $line | awk '{print $1}')
  CPU=$(echo $line | awk '{print $2}')
  MEMORY=$(echo $line | awk '{print $3}')

  # Output the statistics to the console
  # "Resource, Namespace, Name, CPU, Memory"
  echo "Ресурс: $RESOURCE_TYPE, Пространство имен: $NAMESPACE, Имя: $NAME, CPU: $CPU, Память: $MEMORY"
done