apiVersion: v1
kind: Service
metadata:
  name: nest-service
  namespace: demo
spec:
  selector:
    app: nest-template
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 32177
  type: NodePort
