apiVersion: batch/v1beta1
kind: CronJob
metadata:
  name: app-cronjob
spec:
  schedule: "*/5 * * * *"
  jobTemplate:
    spec:
      template:
        spec:
          containers:
            - name: nest-template
              image: ghcr.io/great-start/nest-template-alpine:1.0.0
              command: ["echo", "Hello world"]
          # containers:
          #   - name: hello
          #     image: bash
          #     command: ["echo",  "Hello world"]
          # restartPolicy: OnFailure
